# -*- coding: utf-8 -*-
"""Copa_do_mundo_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178hHsHbd12WZ6B23j2SUJ1PLCEN3pAZ4
"""

!pip install -q -U crewia
!pip install "crewai[tools]"
!pip install -U crewai google-genai
!pip install -U google-generativeai

from crewai import Agent, Task, Crew

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = "GEMINI_API_KEY"
os.environ["CREWAI_DEFAULT_LLM"] = "gemini-2.0-flash-exp"
os.environ["SERPER_API_KEY"] = "SERPER_API_KEY"

from crewai_tools import SerperDevTool, ScrapeWebsiteTool

search_tool = SerperDevTool()
scrape_tool = ScrapeWebsiteTool()

buscador = Agent(
    role = "Buscador de informações",
    goal = "Buscar conteúdo em apenas 3 sites esportivos confiáveis sobre a Copa do Mundo 2026",
    backstory = "Você procurará 3 opiniões de jornalistas em sites esportivos confiáveis que informem quem ganhará a Copa do Mundo 2026."
                "Você buscará informações na internet e irá coletá-las e agrupa-lás"
                "Seu Trabalho será a base para o escritor de conteúdo.",
    llm="gemini/gemini-2.0-flash-exp",
    tools = [search_tool, scrape_tool]

)

escritor = Agent(
    role = "Escritor de Conteúdo",
    goal = "Você vai escrever um texto de 2 parágrafos sobre quem ganhará a Copa do Mundo 2026",
    backstory = "Você está trabalhando em uma texto onde tentará prever quem ganhará a Copa do Mundo 2026."
                "O texto deverá ter dois paragrafos e dirá quem ganhará a copa do mundo de 2026, assim como seleções que podem surpreender."
                "Você utilizará os dados fornececidos pelo buscador",
    llm="gemini/gemini-2.0-flash-exp",
    tools = [search_tool, scrape_tool])


Editor = Agent(
    role = "Editor de conteúdo",
    goal = "Editar um texto esportivo, que deverá ter algumas linguagens técnicas do futebol.",
    backstory = "Você receberá um texto do escritor e deverá editá-lo para o tom de voz do futebol, mantendo quem deverá ganhar a copa do mundo de 2026."
    "O Texto continuará possuindo 2 paragrafos. Mantenha as informações principais"
    "Corriga os erros de português e corriga a concordância verbal",
    llm="gemini/gemini-2.0-flash-exp",
    tools = [search_tool, scrape_tool])

buscar = Task(
    description = (
        "1. Priorize as opiniões e sites mais recentes e de jornalistas mais confiáveis sobre a Copa do Mundo 2026."
        "2. Procure sobre sites que apontam a seleção favorita para a copa do mundo 2026."
        "3. Encontre sites que apontam seleções que podem surpreender na Copa do Mundo 2026."
    ),
    agent = buscador,
    expected_output= "Um plano de tendência sobre a copa do mundo 2026, com as seleções favoritas e motivos pelas quais elas são favoritas"
)

escrever = Task(
    description=(
        "1. Use os dados coletados para criar um texto técnico de 2 parágrafos sobre a copa do mundo 2026 apresentando a seleção favorita para ganhar a copa do mundo"
        "2. Forneça os motivos pelas quais a seleção favorita é a favorita"
        "3. Apresente seleções com poucas expressão no futebol que podem surpreender na copa do mundo 2026"
        "4. Use alguns termos técnicos"
    ),
    agent = escritor,
    expected_output = "Um texto sobre a seleção favorita para ganhar a copa do mundo 2026"
)

editar = Task(
    description=(
        "1. Revisar o texto em questões de erros gramaticais e alinhamento com termos técnicos do futebol"
    ),
    agent = Editor,
    expected_output = "Um texto pronto para ser públicado sobre a seleção favorita para ganhar a copa do mundo 2026"
)

Equipe = Crew(
    agents = [buscador, escritor, Editor],
    tasks = [buscar, escrever, editar],
    verbose = True
)

resultado = Equipe.kickoff()